FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/driver-registrar
COPY . .
RUN go build ./cmd/driver-registrar

FROM registry.svc.ci.openshift.org/ocp/4.0:base
COPY --from=builder /go/src/github.com/kubernetes-csi/driver-registrar/driver-registrar /usr/bin/
ENTRYPOINT ["/usr/bin/driver-registrar"]
